apiVersion: v1
kind: Secret
metadata:
  name: my-app-config
  namespace: rs-6
type: Opaque
data:
  secretPhrase: U2hhemFtIQ==
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: rs-my-app
  namespace: rs-6
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rs-my-app
    spec:
      containers:
        - name: my-app
          image: us.gcr.io/lohika-kub/ht-my-app:3.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: WHO_IS_YOUR_DADDY
              value: Andriy
            - name: SECRET_PHRASE
              valueFrom:
                secretKeyRef:
                  name: my-app-config
                  key: secretPhrase
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
  selector:
    matchLabels:
      app: rs-my-app
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  name: rs-my-app-service
  namespace: rs-6
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: rs-my-app
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-rs-my-app
  namespace: rs-6
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: ReplicaSet
    name: rs-my-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
